---
- hosts: all
  become: true
  roles:
  - initialinstalls
  - pipinstalls
  - dockerinstall


- hosts: manager-group
  become: true
  roles:
  - swarminit

- hosts: worker-group
  become: true
  roles:
  - swarmjoin