---
# tasks file for swarmjoin
- name: "Add node to swarm"
  community.docker.docker_swarm:
    state: join
    advertise_addr: worker
    join_token: "{{ hostvars['manager']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'manager:2377' ]
